apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bonfire-image
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/bonfire-image/bonfire-image@sha256:f275d4ae4df669026e7d8bdd27350594e18c8107c5b6eebdd8db722a0b0bf8f1
        name: container-image
        resources: {}
status: {}
