apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bonfire-image
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bonfire-image
    app.kubernetes.io/part-of: bonfire-image
  name: bonfire-image
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: bonfire-image
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bonfire-image
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gbenhaim-tenant/bonfire-image/bonfire-image@sha256:c6ad54a6d2ba8640aca3d8282459984f924b22ad9d3a5d91e2911d3a308fff4f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
