apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bonfire-image
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bonfire-image
    app.kubernetes.io/part-of: bonfire-image
  name: bonfire-image
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: bonfire-image
status:
  loadBalancer: {}
